# Generated by Django 3.2 on 2022-07-02 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'High'), ('warning', 'Normal'), ('primary', 'Low')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
