# Generated by Django 3.2 on 2022-08-01 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='ユーザー名')),
                ('surname', models.CharField(max_length=10, verbose_name='姓')),
                ('firstname', models.CharField(max_length=10, verbose_name='名')),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='メールアドレス')),
                ('course', models.CharField(choices=[('s1', '理科一類'), ('s2', '理科二類'), ('s3', '理科三類'), ('l1', '文科一類'), ('l2', '文科二類'), ('l3', '文科三類')], max_length=4, verbose_name='科類')),
                ('faculty', models.CharField(blank=True, choices=[('法', '法学部'), ('医', '医学部'), ('工', '工学部'), ('文', '文学部'), ('理', '理学部'), ('農', '農学部'), ('経', '経済学部'), ('教養', '教養学部'), ('教育', '教育学部'), ('薬', '薬学部')], max_length=2, null=True, verbose_name='学部')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='学科')),
                ('grade', models.CharField(choices=[('0期', '0期'), ('1期', '1期'), ('2期', '2期'), ('3期', '3期'), ('4期', '4期'), ('5期', '5期'), ('6期', '6期'), ('7期', '7期'), ('8期', '8期'), ('9期', '9期'), ('10期', '10期'), ('11期', '11期'), ('12期', '12期'), ('13期', '13期')], max_length=3, verbose_name='学年')),
                ('sex', models.CharField(choices=[('未回答', '回答しない'), ('男', '男'), ('女', '女')], max_length=5, verbose_name='性別')),
                ('division', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.division', verbose_name='担当')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group', verbose_name='班')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
