# Generated by Django 3.2 on 2022-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220802_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('s1', '理科一類'), ('s2', '理科二類'), ('s3', '理科三類'), ('l1', '文科一類'), ('l2', '文科二類'), ('l3', '文科三類')], max_length=4, null=True, verbose_name='科類'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('0期', '0期'), ('1期', '1期'), ('2期', '2期'), ('3期', '3期'), ('4期', '4期'), ('5期', '5期'), ('6期', '6期'), ('7期', '7期'), ('8期', '8期'), ('9期', '9期'), ('10期', '10期'), ('11期', '11期'), ('12期', '12期'), ('13期', '13期')], default='13期', max_length=3, verbose_name='学年'),
        ),
    ]
