# Generated by Django 3.2 on 2022-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220802_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('0期', '0期'), ('1期', '1期'), ('2期', '2期'), ('3期', '3期'), ('4期', '4期'), ('5期', '5期'), ('6期', '6期'), ('7期', '7期'), ('8期', '8期'), ('9期', '9期'), ('10期', '10期'), ('11期', '11期'), ('12期', '12期'), ('13期', '13期')], default='13期', max_length=3, verbose_name='期'),
        ),
    ]
