# Generated by Django 3.2 on 2022-08-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
