# Generated by Django 3.2 on 2022-08-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_year',
            field=models.IntegerField(default=2022, max_length=4, verbose_name='入学年'),
        ),
    ]
