# Generated by Django 3.2 on 2022-08-02 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_enrolled_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrolled_year',
            field=models.IntegerField(default=2022, max_length=4, validators=[django.core.validators.MinValueValidator(2009), django.core.validators.MaxValueValidator(2022)], verbose_name='入学年'),
        ),
    ]
