# Generated by Django 3.2 on 2022-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_enrolled_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('s1', '理科一類'), ('s2', '理科二類'), ('s3', '理科三類'), ('l1', '文科一類'), ('l2', '文科二類'), ('l3', '文科三類')], default=None, max_length=4, verbose_name='科類'),
        ),
    ]
