# Generated by Django 3.2 on 2022-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('理科一類', '理科一類'), ('理科二類', '理科二類'), ('理科三類', '理科三類'), ('文科一類', '文科一類'), ('文科二類', '文科二類'), ('文科三類', '文科三類')], default=None, max_length=4, verbose_name='科類'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('法学部', '法学部'), ('医学部', '医学部'), ('工学部', '工学部'), ('文学部', '文学部'), ('理学部', '理学部'), ('農学部', '農学部'), ('経済学部', '経済学部'), ('教養学部', '教養学部'), ('教育学部', '教育学部'), ('薬学部', '薬学部')], max_length=4, null=True, verbose_name='学部'),
        ),
    ]
