# Generated by Django 3.2 on 2022-08-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220803_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_members', to='accounts.division', verbose_name='担当'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='accounts.group', verbose_name='班'),
        ),
    ]
