# Generated by Django 3.2 on 2022-08-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220803_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='division',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
