# Generated by Django 3.2 on 2022-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[(0, '0期'), (1, '1期'), (2, '2期'), (3, '3期'), (4, '4期'), (5, '5期'), (6, '6期'), (7, '7期'), (8, '8期'), (9, '9期'), (10, '10期'), (11, '11期'), (12, '12期'), (13, '13期')], default=13, max_length=3, verbose_name='期'),
        ),
    ]
