# Generated by Django 3.2 on 2022-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('sns_image', models.ImageField(upload_to='')),
                ('good', models.IntegerField(default=0)),
                ('read', models.IntegerField(default=0)),
                ('readtext', models.TextField(default='')),
            ],
        ),
    ]
