# Generated by Django 3.2 on 2022-08-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B303Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('purpose', models.CharField(max_length=255, verbose_name='目的')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('participants', models.ManyToManyField(blank=True, related_name='_clubroom_b303reservation_participants_+', to='clubroom.B303Reservation', verbose_name='参加者')),
                ('person_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
            ],
            options={
                'verbose_name': '部室予約',
                'verbose_name_plural': '部室予約',
            },
        ),
    ]
