# Generated by Django 3.2 on 2022-08-14 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b303reservation',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
        migrations.AlterField(
            model_name='b303reservation',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='責任者'),
        ),
    ]
