# Generated by Django 3.2 on 2022-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubroom', '0003_auto_20220814_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b303reservation',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='目的'),
        ),
    ]
